#!/bin/bash
function usage() {
    echo -e "Usage: $(basename "$0") [options]"
    echo -e ""
    echo -e "OPTIONS:"
    echo -e "  -c\t clean all output files generated by programs"
    echo -e "  --clean\t clean all output files generated by programs"
    echo -e "  -h\t print this message"
    echo -e "  --help\t print this message"
}

# Parse arguments
CLEAN_FLAG=0
while [[ $# -gt 0 ]]; do
    case "${1}" in
    -c | --clean) CLEAN_FLAG=1 ;;
    -h | --help)
        usage
        ecit 0
        ;;
    *)
        echo "ERROR: Unrecognized argument: $1"
        usage
        exit 1
        ;;
    esac
    shift
done

# Jump to the root directory of this repo
DIR=$(pwd)
WDIR=$(dirname "$0")/../
if [ ${WDIR:0:1} != "/" ]; then
    WDIR=$DIR/$WDIR
fi
cd "$WDIR"

# Compile and test programs
function run_test {
    echo "--------------------------------------------------"
    language=$1
    script_dir="src/${language}"
    data_dir="data/SampleTestCases"
    for input_file in ${data_dir}/input*.txt; do
        output_file=${input_file/input/output}
        filename=${input_file##*/}
        no=${filename//[^0-9]/}

        basic_output=${data_dir}/${language}_basic${no}.out
        bash ${script_dir}/basic.sh ${input_file} ${basic_output} &>/dev/null
        if [ -e ${basic_output} ]; then
            diff ${output_file} ${basic_output}
            if [ $? != 1 ]; then
                echo -e "${language} basic     program test ${no}: ${filename} passed"
            else
                echo -e "${language} basic     program test ${no}: ${filename} failed"
            fi
        else
            echo -e "${language} basic     program test ${no}: ${filename} ignored"
        fi

        efficient_output=${data_dir}/${language}_efficient${no}.out
        bash ${script_dir}/efficient.sh ${input_file} ${efficient_output} &>/dev/null
        if [ -e ${efficient_output} ]; then
            diff ${output_file} ${efficient_output}
            if [ $? != 1 ]; then
                echo -e "${language} efficient program test ${no}: ${filename} passed"
            else
                echo -e "${language} efficient program test ${no}: ${filename} failed"
            fi
        else
            echo -e "${language} efficient program test ${no}: ${filename} ignored"
        fi
    done
    echo "--------------------------------------------------"
}

echo 'Test C++'
run_test "cpp"

echo 'Test Java'
run_test "java"

echo 'Test Python'
run_test "python"

# Clean generated output files
if [ ${CLEAN_FLAG} -ne 0 ]; then
    echo 'Cleaning generated output files...'
    rm -rf data/SampleTestCases/*.out
fi

cd "$DIR"
